### ISSUE TITLE
issue with get_item_id_by_name

### ISSUE THREAD

**Issue by ghost** [Cox-Automotive/slackest#13]
channels not making it to get_item_id_by_name when passed; resulting in a response of None when calling the get_channel_id function.  one thing to note - the get_user_id function also calls get_item_id_by_name but get_user_id actually works.

**Comment by randall0319** [comment]
@jusserysig how are you making your get_channel_id call? 
like slack.channels.get_channel_id('#pythonic')
or like slack.channels.get_channel_id('pythonic')?

**Comment by ghost** [comment]
slack.channels.get_channel_id('pythonic')

**Comment by ghost** [comment]
it looks like the get_channel_id is looking up channels using the list() method...which does not appear to be paginating. need to create a list_all method and handle the pagination for this to work for all channels.

**Comment by ghost** [comment]
This isssue caused by the token type ... works for legacy tokens but not for a user token.  may need to look into creating functions to get_channel_id using conversations.
